import Head from 'next/head'
import Image from 'next/image'
import ComingSoon from '../components/comingsoon'
import styles from '../styles/home.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Viou | Coming Soon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ComingSoon />
      
    </div>
  )
}
